[package]
name = "microsandbox-filesystem"
description = "Filesystem backends and guest filesystem support for microsandbox."
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lib]
path = "lib/lib.rs"

[dependencies]
libc.workspace = true
microsandbox-utils.workspace = true
msb_krun.workspace = true
scopeguard.workspace = true
tempfile.workspace = true
tracing.workspace = true

[features]
default = ["prebuilt"]
prebuilt = ["microsandbox-utils/http-client"]

[build-dependencies]
hex.workspace = true
microsandbox-utils.workspace = true
sha2.workspace = true
